[package]
name = "dbtools"
version = "0.1.0"
authors = ["landhb <landhb@github>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Multi-command utility to send auth packets
# generate keys, etc.
[[bin]]
name = "db"
path = "src/main.rs"

[dependencies]
pnet = "0.23.0"
libc = "0.2.66"
failure = "0.1.6"
rand = "0.3"
clap = "2.33.0"
ring = "0.16.11"
openssl = { version = "0.10.28", features = ["vendored"] }
