[package]
name = "tools"
version = "0.1.0"
authors = ["landhb <landhb@github>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bridge"
path = "bridge/src/main.rs"

[dependencies]
pnet = "0.23.0"
libc = "0.2.66"
failure = "0.1.6"
rand = "0.3"
